#!/usr/bin/env ruby
################################################################################
# sanitize-env
################################################################################
# 
# Author: Adrien Thebo
#
# sanitize-env is a ruby script for setting up an environment with standardized 
# values.
#
################################################################################

################################################################################
# module Sanitize
################################################################################
#
# Containing module for all the sanitizing goodies that this script contains.
# 
# Classes to note:
# OperatingSystem   -> base class for all operating systems.
# Shell		    -> base class for shells. 
# Environment	    -> class for a full environment
# Profile	    -> Application specific settings
module Sanitize
	
  ##############################################################################
  # Operating systems
  ##############################################################################
  # Base class for operating system specific settings
  ##############################################################################
  module OperatingSystem
    class Base
      attr_accessor :path
      attr_accessor :cppflags
      attr_accessor :ldflags
      attr_accessor :profiles

      def initialize
	@path = Array.new
	@cppflags = Array.new
	@ldflags = Array.new
	@profiles = Array.new
      end

      def setpath
	if @path.length > 0
	  ENV['PATH'] = @path.join(':')
	end
      end

      def setflags
	if @cppflags.length > 0
	  ENV['CPPFLAGS'] = @cppflags.join(' ')
	end
	if @ldflags.length > 0
	  ENV['LDFLAGS'] = @ldflags.join(' ')
	end
      end

      # Basic setenv method. 
      def setenv
	self.setpath
	self.setflags
	ENV.delete 'LD_LIBRARY_PATH'
      end
    end
    
    ##############################################################################
    # Solaris specific environment settings
    ##############################################################################
    class Solaris < Base

      def initialize
	super
	@path << [ "/opt/csw/gcc4/bin", "/opt/csw/bin", "/bin", "/usr/bin" ]
      end

      def setenv
	@profiles.each do | profile |
	  profile.setenv_solaris(self)
	end
	super
	ENV['SANITIZED_OS'] = 'solaris'
      end
    end

    ##############################################################################
    # Generic linux environment settings
    ##############################################################################
    class Linux < Base
      def initialize
	super
	@path << [ '/usr/sbin', '/usr/bin', '/sbin', '/bin' ]
	@cppflags << '-I/usr/include'
	@ldflags << '-R/usr/lib'
      end

      def setenv
	@profiles.each do | profile |
	  profile.setenv_linux(self)
	end

	super
	ENV['SANITIZED_OS'] = 'linux'
      end
    end
  end

  ##############################################################################
  # Application profiles
  ##############################################################################
  # Base profile
  ##############################################################################
  module Profile
    class Base
      
      def setenv_linux(os)
      end

      def setenv_solaris(os)
      end
    end

    ##############################################################################
    # GHC profile
    ##############################################################################
    class Ghc < Base
      def setenv_linux(os)
	$stderr.puts 'No available profile for GHC on linux'
      end

      def setenv_solaris(os)
	os.path.unshift('/pkgs/gcc/gcc-4.1.0/bin', '/pkgs/ghc/current/bin')
      end
    end

    class SunStudio < Base
      def setenv_linux(os)
	$stderr.puts 'No available profile for Sun Studio on linux'
      end

      def setenv_solaris(os)
	os.path.unshift('/opt/SUNWspro/bin')
	os.ldflags << ['-R/usr/lib', '-R/opt/SUNWspro/lib', '-R/usr/sfw/lib' ]
	os.cppflags << ['-I/usr/include', '-I/opt/SUWNspro/include', '-I/usr/sfw/include']
      end
    end

    class Gcc3 < Base
      def setenv_solaris(os)
	os.cppflags << ['-I/opt/csw/include', '-I/opt/csw/gcc3/include', '-I/usr/include']
	os.ldflags << ['-R/opt/csw/lib', '-R/opt/csw/gcc3/lib', '-R/usr/lib']
      end
    end

    class Gcc4 < Base
      def setenv_solaris(os)
	os.cppflags << ['-I/opt/csw/include', '-I/opt/csw/gcc4/include', '-I/usr/include']
	os.ldflags << ['-R/opt/csw/lib', '-R/opt/csw/gcc4/lib', '-R/usr/lib']
      end
    end
  end

  ##############################################################################
  # Shell specific settings
  ##############################################################################
  # Base class for the shell to execute
  ##############################################################################
  module Shell
    class Base
      def run
	$stderr.puts "Unknown shell type found, blindly executing #{ENV['SHELL']}"
	exec ENV['SHELL']
      end
    end
    
    class Bash < Base
      def run
	puts "Entering shell \"#{ENV['SHELL']}\" with sanitized environment."
	exec "#{ENV['SHELL']} --noprofile --norc"
      end
    end
  
    class Zsh < Base
      def run
	puts "Entering shell \"#{ENV['SHELL']}\" with sanitized environment."
	exec "#{ENV['SHELL']} +f"
      end
    end
  end

  ##############################################################################
  # Specific instance of an environment.
  ##############################################################################
  class Environment
    attr_accessor :system
    attr_accessor :shell

    def initialize
      @system = Sanitize::OperatingSystem::Base.new
      @shell = Sanitize::Shell::Base.new
    end

    def execute
      ENV['SANITIZED'] = '1'
      @system.setenv
      @shell.run
    end
  end
end


################################################################################
# Begin main body of execution
################################################################################

require 'optparse'

# Make sure sanitizing hasn't occurred.
if ENV['SANITIZED'].to_i == 1
  $stderr.puts "Already in a sanitized environment. Exiting."
  exit 1
end

options = Hash.new

opt_parser = OptionParser.new do | opts |
  opts.banner ="Usage #{$0} [options]"

  opts.on('-s', '--system=val', [:solaris, :linux], 'Specify target operating system') do | os |
    options[:system] = os
  end

  opts.on('--prepend-path=val', 'Prepend a string to path') do | path |
    options[:ppath] ||= Array.new
    options[:ppath] << path
  end

  opts.on('--append-path=val', 'Append a string to path') do | path |
    options[:apath] ||= Array.new
    options[:apath] << path
  end

  opts.on('-p', '--profile=val', [:ghc, :sunstudio, :gcc3, :gcc4], 'Load a package profile') do | profile |
    options[:profile] ||= Array.new
    options[:profile] << profile
  end
  opts.separator('                                     Available profiles:')
  opts.separator('                                     [ghc|sunstudio|gcc3|gcc4]')

  opts.on('-h', '--help', 'Display this help screen') do
    puts opts
    exit
  end
end

begin
  opt_parser.parse!
rescue
  $stderr.puts $!
  exit 1
end

################################################################################
# Assemble environment
################################################################################
new_env = Sanitize::Environment.new

new_env.system = case options[:system]
  when :solaris then Sanitize::OperatingSystem::Solaris.new
  when :linux then Sanitize::OperatingSystem::Linux.new
  else
    if ! options[:system].nil?
      $stderr.puts "Error: Unsupported system \"#{options[:system]}\""
      puts opt_parser
      exit 1
    else
      $stderr.puts "Error: --system switch must be specified."
      puts opt_parser
      exit 1
    end
end

# Load profiles
if ! options[:profile].nil? && options[:profile].length > 0
  options[:profile].each do | profile |
    new_env.system.profiles << case profile
      when :ghc then Sanitize::Profile::Ghc.new
      when :sunstudio then Sanitize::Profile::SunStudio.new
      when :gcc3 then Sanitize::Profile::Gcc3.new
      when :gcc4 then Sanitize::Profile::Gcc4.new
    end
  end
end

# Path munging
if ! options[:ppath].nil? && options[:ppath].length > 0
  new_env.system.path.unshift options[:ppath]
end

if ! options[:apath].nil? && options[:apath].length > 0
  new_env.system.path.push options[:apath]
end

# Determine shell type
new_env.shell = case ENV['SHELL']
  when '/bin/bash' then Sanitize::Shell::Bash.new
  when '/bin/zsh' then Sanitize::Shell::Zsh.new
  else Sanitize::Shell::Base.new
end

# Spawn shell in child instance and wait for it in the parent
pid = Process.fork

if pid.nil?
  # Set all environment variables and execute shell
  new_env.execute
else
  Process.waitpid(pid, 0)
  puts 'Exiting sanitized environment.'
end

